apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
  labels:
    app: devops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-demo

  template:
    metadata:
      labels:
        app: devops-demo

    spec:
      containers:
      - name: devops-demo-container
        image: ghcr.io/siddarthareddybaradi/k8s-devops-demo/devops-demo-app:latest
        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret